import Head from "next/head";
import { LocomotiveScrollProvider } from "react-locomotive-scroll";
import { useRef } from "react";
import { isFirefox } from "react-device-detect";
export default function Home() {
  const ref = useRef(null);
  const value = isFirefox ? 1 : 4;

  const options = {
    smooth: true,
    multiplier: value,
  };
  return (
    <LocomotiveScrollProvider options={options} containerRef={ref}>
      {/* <Head>
        <title>Locomotive Scroll</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
      <main ref={ref} className="text-center" data-scroll-container>
        <section
          className="bg-black text-white  h-screen flex flex-col items-center justify-center text-7xl"
          data-scroll-section
          data-scroll
          data-scroll-speed="4"
        >
          <h1>This is the Introduction section</h1>
        </section>

        <section
          className="bg-blue-500 h-screen flex flex-col items-center justify-center text-7xl"
          data-scroll-section
        >
          <h1 data-scroll data-scroll-direction='horizontal' data-scroll-speed='9'>I Love React</h1>
          <h1 data-scroll data-scroll-direction='horizontal' data-scroll-speed='9'>That is why I code everyday</h1>
        </section>

        <section
          className="bg-blue-600 h-screen flex flex-col items-center justify-center text-7xl"
          data-scroll-section 
          id="stick"
        >
          <h1 data-scroll data-scroll-speed='5' data-scroll-sticky data-scroll-target='#stick'>Hey I am Sticky</h1>
          <div className="text-3xl">
            <p>other contents</p>
            <p>other contents</p>
            <p>other contents</p>
            <p>other contents</p>
            <p>other contents</p>
            <p>other contents</p>
            <p>other contents</p>
            <p>other contents</p>
          </div>
        </section>

        <section
          className="bg-blue-50 footer h-screen flex flex-col items-center justify-center text-7xl"
          data-scroll-section
        >
          <h1>Let us end the application with this Footer</h1>
        </section>
      </main>
    </LocomotiveScrollProvider>
  );
}
